name: habitwallet
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  flutter_secure_storage: ^10.0.0

  fl_chart: ^1.1.1

  go_router: ^17.1.0

  flutter_local_notifications: ^20.0.0
  uuid: ^4.5.2
  file_picker: ^10.3.10
  open_filex: ^4.7.0
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.11.0
  drift_dev: ^2.31.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1

  mocktail: ^1.0.4

  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Chillax
      fonts:
        - asset: assets/font/Chillax-Variable.ttf
